### ISSUE TITLE
Why the white line doesn't show?

### ISSUE THREAD

**Issue by THEONE10211024** [geftimov/android-pathview#11]
In my own machine ,it works just fine,but in my colleague's machine ,the white line doesn't show?We share the same code.Could you please tell me why?
![qq 20150803121457](https://cloud.githubusercontent.com/assets/11347899/9030782/36c84412-39da-11e5-9873-df71d886dda8.png)
![qq 20150803121530](https://cloud.githubusercontent.com/assets/11347899/9030783/36f8487e-39da-11e5-8b25-55126a8ef60d.png)

**Comment by geftimov** [comment]
Can you provide more information about :
1) Device information
2) Android version

**Comment by THEONE10211024** [comment]
Mine:
Android build target:Android 4.0
JDK:jdk1.7.0_45

My colleague's:
Android build target:Android 4.0
JDK:jdk1.6.0_45
He built with ant and I built with ADT default apk tool

**Comment by THEONE10211024** [comment]
I figured out why it doesn't show in my colleague's machine,he is using proguard.config file and I don't.

**Comment by geftimov** [comment]
Oh ok.
Is the issue done?

**Comment by THEONE10211024** [comment]
yes，thanks！

**Comment by geftimov** [comment]
Well I did nothing.

**Comment by THEONE10211024** [comment]
Hi,geftimov.I've found out the problem but I don't konw how to fix it.The problem is that when I add the proguard-project.txt file ,the white line gone ,and when I remove the file ,the white line shows up . I don't konw why.
Belowing is the printscreen of the proguard-project.txt file, and we only add one line code there!
![qq 20150804195152](https://cloud.githubusercontent.com/assets/11347899/9060038/7f58fd62-3ae2-11e5-8af1-057e744e304f.png)

**Comment by geftimov** [comment]
android-pathview uses inner library for animating svgs.
It is as dependency :
dependencies {
    compile files('libs/androidsvg-1.2.1.jar')
}
Maybe when you want to strip the inner library 
PathView does not work as expected.
