### ISSUE TITLE
Animate paths sequentially

### ISSUE THREAD

**Issue by CharlesNascimento** [geftimov/android-pathview#13]
Hello! Is it possible to animate the paths sequentially, insteady of in parallel? Congratulations for your great work, thanks!

**Comment by geftimov** [comment]
It should be possible, because you have a List of paths and their duration.
Probably a simple flag in java should do the trick and the implementation should
wait for the duration of the following path to be able to start the animation of the second.

**Comment by geftimov** [comment]
Thanks , looks great.
I will upload it to maven today.

**Comment by geftimov** [comment]
From version 1.0.7

**Comment by CharlesNascimento** [comment]
Thanks, it's a pleasure to help! :)
