### ISSUE TITLE
android:allowBackup should not be used in library

### ISSUE THREAD

**Issue by b3stia** [geftimov/android-pathview#16]
Hi,
property:  "android:allowBackup" shouldn't be used in library because it cause an error with building app on prodction

**Comment by geftimov** [comment]
You are right.
Forgot to remove it.
I will make an version today and change it.

**Comment by b3stia** [comment]
ok, Great!

**Comment by geftimov** [comment]
Fixed on [1.0.8](https://github.com/geftimov/android-pathview/releases/tag/1.0.8).
