### ISSUE TITLE
A problem of Memory

### ISSUE THREAD

**Issue by zhouhytx2010** [geftimov/android-pathview#17]
Hi, When I use the pathview, memory has been growing, how can I reduce the memory？

**Comment by geftimov** [comment]
Can you show screenshot of the Memory monitor in Android studio when using the library?

**Comment by zhouhytx2010** [comment]
[1.docx](https://github.com/geftimov/android-pathview/files/70635/1.docx)
I have upload some pics in the word file 1.docx

**Comment by zhouhytx2010** [comment]
I just play the svg file repeat

**Comment by geftimov** [comment]
It looks fine to me, not an expert on memory management , but the library :
1) Loads SVG in memory.
2) Get the path from the svg.
3) Animate the paths with proper percentage.

Plus starting the application and the activity I think the 9-11 MB or RAM are ok.

**Comment by zhouhytx2010** [comment]
you try to quick click the pathview of this demo any times, you can discover the memory grows quickly. Should I do something to solve this problem？

**Comment by geftimov** [comment]
Ok I will investigate it.
