### ISSUE TITLE
setting fillAfter or fill in PathView tag

### ISSUE THREAD

**Issue by mobi-life** [geftimov/android-pathview#18]
Hi
First I should say thanks for your awesome library .
If there was a property in PathView tag something like **app:fillAfter="true"** or **app:fill="true"** would be very useful , because some times we need to use it as a special SVG image view for just showing whole image without animation , I know there is some libraries for showing SVG images out there , but it would be good to have just one library that can animate SVG images and also showing them statically .
For now I'm doing it by writing **PathView.setFillAfter(true);** in code and setting animation duration to 1 for showing it immediately , but you know it's a little dirty :P
Also if you like I can help you in making these changes in code to merge with master branch.

**Comment by geftimov** [comment]
Great suggestions.
Please help if you want. This is open source library and with more contributors will become better.
Thanks.

**Comment by mobi-life** [comment]
@geftimov Sure , I will try to make changes and upload it

**Comment by geftimov** [comment]
@mobi-life Done for 1.0.9 thanks for the contributions.
