### ISSUE TITLE
Can't get Colors of the SVG?

### ISSUE THREAD

**Issue by AruLNadhaN** [geftimov/android-pathview#2]
I am using a Colored Svg as source. It traces the path of the svg. But I need to color the svg after tracing the path.

Is there a way to do it?

**Comment by geftimov** [comment]
Hello AruLNadhaN,

You can try animating the object property and change the color after the animation is done.
Here is an example: 

final ObjectAnimator anim = ObjectAnimator.ofFloat(pathView, "percentage", 0.0f, 1.0f);
				anim.setDuration(700);
				anim.setInterpolator(new LinearInterpolator());
				anim.addListener(new Animator.AnimatorListener() {
					@Override
					public void onAnimationEnd(Animator animation) {
						pathView.setPathColor(Color.GREEN);
					}
				});
				anim.start();

**Comment by geftimov** [comment]
@AruLNadhaN 
Do this answer your quesition ?

**Comment by geftimov** [comment]
@AruLNadhaN 
Now you can just use the pathAnimator like this.

pathView.getPathAnimator()
    .listenerEnd(new AnimationListenerEnd())
    .start();
