### ISSUE TITLE
When I use getSequentialPathAnimator (), draw a lot of extra lines

### ISSUE THREAD

**Issue by MartinBZDQSM** [geftimov/android-pathview#28]
![image](https://cloud.githubusercontent.com/assets/10938249/18168328/b2568e56-7087-11e6-8ac5-750c4292f09f.png)
Like the one shown above ,When I use the code below, it happens.

```
     pathView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
//                pathView.getPathAnimator().
                pathView.getSequentialPathAnimator().
                        delay(100).
                        duration(5000).
                        interpolator(new AccelerateDecelerateInterpolator()).
                        start();
```

**Comment by geftimov** [comment]
This looks like a bug.
Can I have the svg?

**Comment by MartinBZDQSM** [comment]
it`s in your sample https://github.com/geftimov/android-pathview/blob/master/sample/src/main/res/raw/flag_usa.svg

**Comment by geftimov** [comment]
Ok thanks will see what can I do.

**Comment by MartinBZDQSM** [comment]
thx

**Comment by MartinBZDQSM** [comment]
OMG, I know why is the result of this, because when I read your code and modify your code in SvgUtils:
![image](https://cloud.githubusercontent.com/assets/10938249/18266556/cb04f63a-744d-11e6-9a71-f31021b95783.png)

very sorry 
╥﹏╥...

**Comment by geftimov** [comment]
So you mean this is probably the fix for the bug?

**Comment by MartinBZDQSM** [comment]
yes, in your code it`s prove to be true.

i`m so sorry,i should not to modify it.

**Comment by MartinBZDQSM** [comment]
I removed the parallel animation and modified the fill animation .Now the animation is like that：
![woman](https://github.com/MartinBZDQSM/PathDraw/blob/master/app/src/main/res/raw/woman.gif)
My link : https://github.com/MartinBZDQSM/PathDraw

**Comment by geftimov** [comment]
I go through the library and the blog.
I am really impressed, nice job.
