### ISSUE TITLE
Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 2124 (SVG Loader)

### ISSUE THREAD

**Issue by mradzinski** [geftimov/android-pathview#3]
The sample project crashes with an internal platform error (no stacktrace). Crashes on devices from API 14 till API 19, different device models, emulated and physical devices as well. Works on API 19 and above.

**Comment by geftimov** [comment]
@mradzinski 
I will investigate that.

**Comment by geftimov** [comment]
@mradzinski 
I have made some changes to the library and now it should work for all versions.

**Comment by geftimov** [comment]
Closing this issue
