### ISSUE TITLE
How to do reversed animation?

### ISSUE THREAD

**Issue by lion4ik** [geftimov/android-pathview#31]
I mean animate from drawn state to erased state. Actually, I want to do cyclic animation for progress loader, which will be animate painting then animate erasing then again painting and then erasing and so on... Could you give me a hint how to do it ?

**Comment by geftimov** [comment]
Actually I did something like that.
Instead of using the animations you must set the progress yourself. 
The call is:
```
pathView.setPercentage(0.5f);
```
This will give you exactly half of the svg path animation, so you can hook it up with something 
that is changing that value from 0 to 1 and then from 1 to 0.
Should be easy.
