### ISSUE TITLE
Fillafter animation

### ISSUE THREAD

**Issue by diabloo** [geftimov/android-pathview#33]
Hi, i'm using your library and it's great , but i was wondering if there was a possibility to animate color filling

**Comment by geftimov** [comment]
@diabloo Can you describe in more details what do you mean?

**Comment by diabloo** [comment]
i have a colored svg , i use : 
`pathView.useNaturalColors(); `
`pathView.setFillAfter(true)`
 i want to know if it's possible to fill with an animation like in this [library](https://github.com/JorgeCastilloPrz/AndroidFillableLoaders) but i want to achive this with the natural colors.
ps :sorry for my english

**Comment by geftimov** [comment]
No worries , your English is perfect.

It is not possible unfortunately.
This effect is beautiful but will change the course of this library.

But I think you can easily use the library that you pointed. Seems legit 👍
