### ISSUE TITLE
stroke-linecap is being ignored

### ISSUE THREAD

**Issue by casper1149** [geftimov/android-pathview#7]
Hi,

I am trying to draw a path, smth like an arch with rounded corners, however "stroke-linecap" parameter seems to be skipped and so the result image is without rounded corners.

svg example:
\<svg viewBox="0 0 144 144"\>
\<path fill="none" stroke="#FFFFFF" stroke-width="16" stroke-linecap="round" stroke-miterlimit="10" d="M117.3 26.7 C105.7 15.2,89.7 8,72 8"/\>
\</svg\>

layout:
        <com.eftimoff.androipathview.PathView
            xmlns:app="http://schemas.android.com/apk/res-auto"
            android:id="@+id/archLeftPathView"
            android:layout_width="180dp"
            android:layout_height="180dp"
            app:pathColor="@android:color/white"
            app:svg="@raw/arc_left"
            app:pathWidth="60"/>

may be I am missing smth?

You can verify the svg using smth like http://www.rapidtables.com/web/tools/svg-viewer-editor.htm

**Comment by geftimov** [comment]
@casper1149 

Well , unfortunately when getting the path from the svg i use only the color and the width.

The Paint object itself draws stroke with anti-alias.
The solution is to catch and set the stroke-linecap.

Is this good for you?

**Comment by geftimov** [comment]
@casper1149 

I have done changes in the library and it should work for you without problems.
It is for version 1.0.4.

Thanks for the feedback,
Georgi Eftimov

**Comment by casper1149** [comment]
@geftimov great, thank you, I will verify the fix

**Comment by casper1149** [comment]
@geftimov hm, stroke-width ok, but what about stroke-linecap, for me it still draws a line without rounded ends
