### ISSUE TITLE
help me! why ?

### ISSUE THREAD

**Issue by tosslife** [geftimov/android-pathview#8]
dependencies{
     compile 'com.eftimoff:android-pathview:1.0.6@aar'
}

    <com.eftimoff.androipathview.PathView
        android:id="@+id/pathView"
        android:layout_width="150dp"
        android:layout_height="150dp"
        app:pathColor="@android:color/white"
        app:pathWidth="10"
        app:svg="@raw/settings"/>

in  activity xml  , running but no find

**Comment by geftimov** [comment]
@tosslife 
Did you find the library?

**Comment by tosslife** [comment]
sorry，it is my problem , Download your library and simple demo,

**Comment by geftimov** [comment]
ok not a problem,
please write me an email (see it in my profile)

**Comment by tosslife** [comment]
i send email  by bian.xiaodong@zuiemai.com

**Comment by THEONE10211024** [comment]
Did you solve the problem ? I have the similar problem
