### ISSUE TITLE
why i can't addCircle to the path ?

### ISSUE THREAD

**Issue by tarek360** [geftimov/android-pathview#9]
hi,

when i add Circle to the path using this code :
path.addCircle(width/2,width/2,width-padding, Path.Direction.CW);

pathview make Circle is not shown

**Comment by geftimov** [comment]
The problem is all figures except the path are not drawn to the canvas.
When i started developing this library there was support for circle ....
But i had problems with older versions so i drop the support.

**Comment by THEONE10211024** [comment]
Could you please the reason why the Circle is not shown? I have the similar problem!

**Comment by THEONE10211024** [comment]
Could you please the reason why the Circle is not shown? I have the similar problem!

**Comment by geftimov** [comment]
The library follows and animates only the paths.
The circle have different projectile.

I will look into it and keep you posted.
